---
title: "Acerca del curso"
editor: visual
---

Bienvenido al sitio web del Curso de Estadística Aplicada con R organizado por la Facultad de Biología de la Universidad Central del Ecuador, a realizarse entre el 3 y el 12 de abril de 2023.

Esta es la primera vez que voy a dictar un curso a este nivel de profundidad, por lo que me he encontrado incontables horas preparando los materiales y su contenido de la manera en que a mí me hubiese gustado aprender Estadística durante mi tiempo cursando un pre-grado en Biotecnología, que como muchas otras carreras, forman a sus estudiantes con un enfoque mayoritariamente práctico en técnicas de laboratorio pero que flaquea en el aspecto de la matemática y la estadística aplicadas, condenándonos -aunque suene trágico- a recolectar datos y luego no saber por donde comenzar a hacer su análisis porque no resulta tan fácil el tratar de hacer un ANOVA en Excel, o como en mi caso, sentarme con una calculadora a aplicar las fórmulas de un Diseño en Bloques Completamente al Azar, como arcaicamente aprendí en mi clase de diseño experimental.  

Por esta razón, teniendo en cuenta el reto que constituye el impartir un curso 100% en línea, he guardado especial cuidado en estructurar su contenido de la manera que espero resulte ser la más participativa posible para que el transcurso de las siguientes 20 horas de clase no se limiten a un monólogo de mi parte complementado de 20 horas más de mi total ausencia durante tu aprendizaje autónomo.

Por el contrario, espero con tu ayuda, brindar un ambiente lo más cercano a lo que una clase presencial pudiera brindar mediante tu activa participación ya sea llevando a cabo los distintos ejercicios que cubriremos o preguntando cualquier duda que pueda surgir durante y fuera de la hora de clase, sacándole el jugo a las distintas herramientas que la tecnología actual nos ofrece.

Sin más que esperar que los próximos días sean lo más beneficiosos, sobre todo para tí, te agradezco por la confianza de haberte inscrito y ser parte de lo que espero sea un ciclo continuo de capacitaciones en materia Estadística, y del cual, este curso es el "piloto" que se ha dado tras una activa coordinación con el Docente de la UCE, Javier Torres, a quién agradezco profundamente la oportunidad de volver a una de mis pasiones: la enseñanza.

Mauricio Moreno